[package]
name = "sample-rt"
version = "0.1.0"
authors = ["HydryHydra"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
windows="0.3.1"
bindings = { path = "bindings" }
